version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    # image using noauth if no credentials are provided,
    # which is fine for testing on localhost
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: 'testroot'
    #  MONGO_INITDB_ROOT_PASSWORD: 'testpw'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
